import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["tests/**/*.test.ts"],
    // Snapshot files are generated by the CLI, not the tests.
    snapshotFormat: { printBasicPrototype: false },
  },
});
